### ISSUE TITLE
About Pre-trained Model problem

### ISSUE THREAD

**Issue by wodylm** [jeffreyhuang1/two-stream-action-recognition#16]
Hi,
    when I download Pre-trained model, I can not unpack the files. can you upload the Pre-trained Model again.
    thanks

**Comment by jeffreyhuang1** [comment]
Hi,

Sorry for the late reply. 
Actually, I curious about how did you "unpack" the pretrained model, since the correct way to load the pretrained model is via the function `torch.load()`. 

Maybe you could try this method! If it is still broken, please feel free to let me know!! I will re-upload it immediately.

Jeffrey

**Comment by wodylm** [comment]
Thanks a lot
