### ISSUE TITLE
About motion_cnn.py,why data loading needs so much time ?it seems to be close to the batch time.

### ISSUE THREAD

**Issue by VictorLeeLk** [jeffreyhuang1/two-stream-action-recognition#20]
hello,When I run the motion_cnn.py,I get some questions,As follows,
1、About motion_cnn.py,When I set the bath_size as more than 32 such as 64, I find  the program stuck at the training stage, and some time it run fast ,but then it stuck.(My GPU is GTX1080ti,when i run the command  nvidia-smi,It shows that I just use less than 4G memory)
2、Also, I find that the data loading time  is similar to the batch time,It makes me confused,Why data loading needs so long ,and similiar to batch time,does the model trainning (batch time-data loading time) need little time?

hope to get your answer,thanks!

**Comment by jeffreyhuang1** [comment]
Hi,
For the first question, the reason why the training process will temporally stuck is that the model is still processing on CPU(including I/O and resizing image to the size of model input). If you raise the number of  batch size, the time of preprocessing will also increase.  Therefore, it is normal that the time on CPU will increase, due to the hardware limitation.

For the second question, to make it more precise, batch time means the time consumption on GPU, and the data time means the time consumption on CPU.

If you would like to this verify this question, you can test the code in  [here](https://github.com/jeffreyhuang1/two-stream-action-recognition/blob/master/dataloader/spatial_dataloader.py#L35) and figure out the reason why it takes so much time on CPU.

I hope my clarification has been helpful.
Jeffrey
