### ISSUE TITLE
The dataset mismatches with the code 

### ISSUE THREAD

**Issue by liushaocan** [jeffreyhuang1/two-stream-action-recognition#59]

**Comment by jeffreyhuang1** [comment]
First of all, a friendly reminder, initial comment stays even if the messege is edited.
[
<img width="641" alt="Screen Shot 2019-06-19 at 9 12 32 PM" src="https://user-images.githubusercontent.com/25765951/59768461-fdc95e80-92d6-11e9-945a-fdcdd579860d.png">
](url)

Since this is an open repository so I believe it is not my duty to make it "worth your while". If you think this project doesn't meet your demand, the door is right there. Judging from the level of vacancy of your profile, I'm guessing that the only reason for you to visit Github is to scour for code, without ever thinking about giving back to the community. 

FYI
It was clearly stated, in README, that my dataloader only served as an example and user should write their own dataloader to fit the data on their own device, so next time before coming with that kind of attitude, please read the whole damn thing.
