### ISSUE TITLE
Testing realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [jeffreyhuang1/two-stream-action-recognition#6]
How do I test it either realtime or using video as an using through VideoCaputre?

**Comment by jeffreyhuang1** [comment]
Hi, first, for realtime testing, since the two-stream method is based on the voting of frame level prediction over whole video, I think the speed might be able to reach realtime level.

Second, if you want to test it directly on videos through VideoCapture, I think you can include the stage of extracting the rgb frames and computing optical flow in your function.

Jeffrey
